# Dependencies
markdown:         redcarpet
highlighter:      pygments
permalink: /:year/:month/:day/:title

# Permalinks
permalink: /:year/:month/:day/:title
relative_permalinks: true

# Setup
title:            DriftingDog
tagline:          'A Jekyll theme'
description:      '一只编程狗的乌有之乡'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
